### ISSUE TITLE
How can I get the next stateId or eventId of the document?

### ISSUE THREAD

**Issue by yuedefeng** [js-ojus/flow#106]

**Comment by yuedefeng** [comment]
I use the following code , is right ?
-----------------------------------------------
myDocument, err := Documents.Get(tx, DocTypeID(1), DocumentID(1))
retMap, err := DocTypes.Transitions(DocTypeID(1), myDocument.State.ID)

**Comment by yuedefeng** [comment]
as following codes, Maybe "DocEventID(3) " need I  bind to my business logic ?
----------------------------------------------------
myDocEvent, err := DocEvents.Get(DocEventID(3))
	myWorkflow, err := Workflows.Get(WorkflowID(1))
	groupIds := []GroupID{GroupID(1)}
	newDocStateId, err := myWorkflow.ApplyEvent(tx, myDocEvent, groupIds)

**Comment by js-ojus** [comment]
> ## I use the following code , is right ?
> myDocument, err := Documents.Get(tx, DocTypeID(1), DocumentID(1))
> retMap, err := DocTypes.Transitions(DocTypeID(1), myDocument.State.ID)

Yes, once you have the transitions defined, this query gives you the set of possible next states, together with which actions would lead to such transitions.

**Comment by js-ojus** [comment]
> ## as following codes, Maybe "DocEventID(3) " need I bind to my business logic ?
> myDocEvent, err := DocEvents.Get(DocEventID(3))
> myWorkflow, err := Workflows.Get(WorkflowID(1))
> groupIds := []GroupID{GroupID(1)}
> newDocStateId, err := myWorkflow.ApplyEvent(tx, myDocEvent, groupIds)

The list of group IDs should specify which groups (and users, through their singleton groups) should receive the notification of the document state transition.  Once the event is applied, all those groups shall have the notification sent to their respective mailboxes.

Please check `message.go` and `mailbox.go`.  Also, see `node.go`, line 134 onwards.  In particular, see line 169 onwards for how the message gets dispatched to mailboxes.  The methods `determineRecipients` and `postMessage` contain the logic for notifications.

**Comment by js-ojus** [comment]
@yuedefeng : ping!

**Comment by js-ojus** [comment]
@yuedefeng : Closing this issue.  Please open one should you have another question.
