### ISSUE TITLE
Check group id is singleton when create a new event?

### ISSUE THREAD

**Issue by zhushh** [js-ojus/flow#109]
Hi, I have read your code and has a little confused. When creating a new event without check the group id is singleton, that may be will cause we do not know who create this event if the group is type of 'G' and has more than one user. Yeah, the workflow also do not check the group type, so the event can be applied. Is there a problem?

**Comment by js-ojus** [comment]
@zhushh Thanks for your interest in `flow`.

The caller is expected to ensure that the group specified is a singleton group (`S`).  However, I am treating this as a desirable check.  So, I shall incorporate it.

**Comment by zhushh** [comment]
OK, I understand now. Thank you very much.
