### ISSUE TITLE
Can you perfect the example again?

### ISSUE THREAD

**Issue by 3xxx** [js-ojus/flow#111]
Thank you very much for the previous example. 
Can you perfect the example again?

For example, when I create a new documents, do I create their events at the same time? Or create a new event and apply it to workflow when I clicks the action button?

In the list of documents presented to the user, for each document, is it right to list all possible actions and next states according to transition? When the user clicks on the action button, do I just create a new event and then apply it to workflow?

When I create a new event, it returns DocEventID, but what workflow applyevent needs is an DocEvent. Feel that I do is not correct.

**Comment by js-ojus** [comment]
1. When you create new documents, their events need **_not_** be created at the same time.  Events should be created and applied in response to user actions (or system events).

1. Whether you list all possible actions in a list of documents is up to you.  In my opinion, the possible actions - for a given user - on a given document, are best made available in the detailed view of that document (not in a document list view).

1. Yes, when the user clicks on an action button, we can create the corresponding event instance, and apply it to the document's workflow.

1. With a `DocEventID`, you can fetch the corresponding event instance using `DocEvents.Get` (please see https://github.com/js-ojus/flow/blob/a4bc40995242db9b2cd949eea10f0379a1dab274/docevent.go#L295 onwards).

**Comment by 3xxx** [comment]
Thank you for your patient answer, I will continue to try according to your suggestion.
