### ISSUE TITLE
Why is unique(doctype_id, docstate_id), but not unique(doctype_id, docstate_id, ac_id)？

### ISSUE THREAD

**Issue by zhushh** [js-ojus/flow#112]
Hi, I have some question about workflow node after reading **wf_workflow_nodes.sql**. If I want to create two workflows for the same doctype, for example, A -> B -> C and E -> B -> F. Now, since the constraints of table **wf_workflow_nodes.sql**, the two flows on the node B will has the same **ac_id** and will have the same access context which means the same permission. So, why not change to unique(doctype_id, docstate_id, ac_id), so we can give the different permission to node B in the two or more wrokflows?

**Comment by js-ojus** [comment]
@zhushh Thank you for your interest in `flow`.

The thinking behind that decision was that a one-to-one correspondence between `DocType` and `Workflow` eases reasoning about the access contexts and nodes through which the document potentially passes.

However, I shall be very interested in a scenario that you can construct for a good case of allowing the same `DocType` with multiple `Workflow`s.

**Comment by zhushh** [comment]
@js-ojus Thank you for your explanation.

I do not look carefully **wf_workflows.sql**. Now I understand why this is the case. And I can solve my problem by merge A -> B -> C and E -> B -> F into one workflow like this:
Z -> A -> B -> C
Z -> E -> B -> F
So，we just need one wrokflow to solve my problem by adding one more node at the beginning.

**Comment by zhushh** [comment]
In my case, there are different people who will create workflow, and the name of doctype can be identical. So it will occur that the `doctype` will have two workflow. Or I should process this case as an error and warn the user that he can not create the same doctype and workflow. I mean, I want user do it like this, how do you think?

**Comment by zhushh** [comment]
I create an api to support that people can post a request to create a workflow like this:
```json
{
    "workflow": {
        "name": "document example",
        "initial": "docState1",
        "doctype": "docType1",
        "docstates": [
            "docState1", "docState2", "docState3", "docState4"
        ],
        "docactions": [
            "docAction12", "docAction23", "docAction34"
        ],
        "contexts": [
            "accCtx1", "accCtx2"
        ],
        "transitions": [
            {
                "fromState": "docState1",
                "toState": "docState2",
                "action": "docAction12"
            },
            {
                "fromState": "docState2",
                "toState": "docState3",
                "action": "docAction23"
            },
            {
                "fromState": "docState3",
                "toState": "docState4",
                "action": "docAction34"
            }
        ],
        "nodes": [
            {
                "nodeName": "node1",
                "nodeType": "begin",
                "docstate": "docState1",
                "context": "accCtx1"
            },
            {
                "nodeName": "node2",
                "nodeType": "linear",
                "docstate": "docState2",
                "context": "accCtx2"
            },
            {
                "nodeName": "node3",
                "nodeType": "linear",
                "docstate": "docState3",
                "context": "accCtx1"
            }
        ]
    }
}
```

**Comment by js-ojus** [comment]
@zhushh 

> In my case, there are different people who will create workflow, and the name of doctype can be identical. So it will occur that the `doctype` will have two workflow. Or I should process this case as an error and warn the user that he can not create the same doctype and workflow. I mean, I want user do it like this, how do you think?

`DocType` names **must** be unique.  It is an error to have multiple document types with the same name.  Please look at `wf_doctypes_master.sql`.  It has a uniqueness constraint on `name`.

**Comment by js-ojus** [comment]
@zhushh Incidentally, I am currently working on the next version of `flow`.  The new version runs as a service with a REST API.  I hope to make an initial release soon.

**Comment by zhushh** [comment]
> @zhushh Incidentally, I am currently working on the next version of `flow`. The new version runs as a service with a REST API. I hope to make an initial release soon.

It is nice to here this news and I am looking for it.

**Comment by js-ojus** [comment]
@zhushh 

- Document types, document actions, _etc._ should be created first.
- Workflow definition should have only node definitions as part of it.

**Comment by zhushh** [comment]
> @zhushh
> 
> * Document types, document actions, _etc._ should be created first.
> * Workflow definition should have only node definitions as part of it.

Yeah, I know and I have achieved it simply. Thanks a lot for your help.

**Comment by js-ojus** [comment]
Welcome!
