### ISSUE TITLE
Tx is nil bug!!

### ISSUE THREAD

**Issue by zhushh** [js-ojus/flow#116]
@js-ojus 

Hi, I have found that the following code is a bug:

```go
	var tx *sql.Tx
	if otx == nil {
		tx, err := db.Begin()
		if err != nil {
			return 0, err
		}
		defer tx.Rollback()
	} else {
		tx = otx
	}
```

here `tx, err := db.Begin()` will make a temporary variable `tx`, so out of the if statement, tx also will be a nil value. Thus, when you call the interface which need parameter `*sql.Tx` and you give a nil to it, it will cause a panic. For example:

```go
        gid, err := flow.Groups.New(nil, "nike", "G")
```
I give `nil` to `Groups.New` because I have called RegisterDB to make db is not null.

We can use this code to fix it:
```go
    var tx *sql.Tx
    if otx == nil {
        var err error
        tx, err = db.Begin()
        if err != nil {
            return 0, err
        }
        defer tx.Rollback()
    } else {
        tx = otx
    }
```

**Comment by js-ojus** [comment]
@zhushh Ouch, ouch!  Good catch!  I fell into a pretty basic Go trap. :-(

I never discovered this because, in all my code, I created a top-level transaction that I passed in.

I shall correct this.
