### ISSUE TITLE
flow-ui online

### ISSUE THREAD

**Issue by 3xxx** [js-ojus/flow#119]
[flow-ui](http://111.230.181.182:8080) online #113
In order to facilitate everyone to understand and use flow, I wrote a demo with vue.js+element+vue-element-extends+beego and put it on tencent cloud. It is just a preliminary one,at present it has the function of adding, but cant delete and modify.
![Snap3](https://user-images.githubusercontent.com/10678867/54489836-9a9cea00-48eb-11e9-816b-d93b4ccc5b2d.png)
![Snap5](https://user-images.githubusercontent.com/10678867/54489837-9e307100-48eb-11e9-88fd-0032fdf3e496.png)

**Comment by js-ojus** [comment]
@3xxx 👍 

Thanks so much for this!
