### ISSUE TITLE
Can you make a easy turtorial?

### ISSUE THREAD

**Issue by glepnir** [js-ojus/flow#120]
Hi the information of flow is too little。can you make a turtorial that a blog or a website? i think is very useful for  some people who is new beginner of flow.

**Comment by js-ojus** [comment]
@taigacute 

Thank you for your interest in `flow`.  Sure, I shall prepare a tutorial.

**Comment by glepnir** [comment]
@js-ojus  that's good, A good tutorial will attract more people to interest `flow`

**Comment by 3xxx** [comment]
![detail](https://user-images.githubusercontent.com/10678867/56857468-90691380-69a0-11e9-8a21-3e5811f878b9.png)
![timeline](https://user-images.githubusercontent.com/10678867/56857469-9101aa00-69a0-11e9-82bb-f52d3053612a.png)

**Comment by js-ojus** [comment]
@3xxx 

👍 Glad to see more progress!

**Comment by glepnir** [comment]
the pic seems like a document not a turtorial?

**Comment by 3xxx** [comment]
@taigacute That example is just a step by step test.

**Comment by js-ojus** [comment]
@taigacute @3xxx 

I am finishing up a few urgent pieces of work in my consulting engagements.  Kindly bear with me.  I shall return to this.

Also, there is an overhaul being made to `flow`.  Please keep watching the `0.9` branch for more details.  Thank you all!

**Comment by guoguoxiaozhu** [comment]
Thank for the flow lib and i glade to find the workflow lib in golang.
i test the lib last week and , maybe  i am a newer to sql and golang ,  i found that when  new  a child document , the data is query in mysql but is error  at parse the ctime , i am not sure  
pdoc, err := Documents.Get(nil, input.ParentType, input.ParentID)->
err := row.Scan(&elem.Path, &elem.AccCtx.ID, &elem.Group.ID, &elem.Group.Name, &elem.Ctime, &elem.Title, &elem.Data, &elem.State.ID, &elem.State.Name)->
err := r.rows.Scan(dest...)

the error :
err : sql :  Scan  errors on colum  index 4, name "ctime": unsupported Scan ,  storing  driver.value  type []uint8
and return err
