### ISSUE TITLE
Can't delete groups which received messages

### ISSUE THREAD

**Issue by LanfordCai** [js-ojus/flow#121]
If a group received messages and a mailbox created for it, then an error would be raised if you try to delete it.

```
update or delete on table "wf_groups_master" violates foreign key constraint "wf_mailboxes_group_id_fkey" on table "wf_mailboxes"
```

Maybe `Groups.Delete` should also delete the Group mailbox, or Mailboxes should provide a `Delete` method?

**Comment by js-ojus** [comment]
@LanfordCai : Thank you for your interest in `flow`.

I shall check this, and get back to you.

**Comment by js-ojus** [comment]
@LanfordCai : Apologies for the delay.

It was a design decision, to preserve history for audit purposes.  Thus, once an activity is performed by a user (singleton group), and a record is generated for it, there is no option to delete the group.

**Comment by LanfordCai** [comment]
@js-ojus Got it, thank you~
