### ISSUE TITLE
good job~

### ISSUE THREAD

**Issue by 3xxx** [js-ojus/flow#76]
This workflow is what I need, and I'm going to make it in beego.Thanks.

**Comment by js-ojus** [comment]
Thanks @3xxx for your kind words!

`flow` is in rapid development.  Its first production use is going to roll our over the next couple of weeks.  As such, there are bug fixes and minor enhancements taking place almost everyday.  Currently, there is some flux in the API.  Minor (and infrequent) DB schema changes may take place too.

Please file bug reports and feature requests as you encounter them.  Thanks!
