### ISSUE TITLE
Stalled

### ISSUE THREAD

**Issue by gedw99** [js-ojus/flow#99]
Is this project stalled.
Are you going to put any examples in the repo.

I ask because it's quite useful code base for BPM

**Comment by js-ojus** [comment]
Thanks @gedw99, for your kind words.

I have a project that uses this library in production.  I have been trying to observe it in production, while also collecting feedback from the developers using the library.  I do not yet have a concrete set of changes that have merited new commits.

Nonetheless, your point is taken about examples.  I shall gradually add examples.  Thanks again!

**Comment by gedw99** [comment]
That would be awesome.

Really looking forward to trying it out and contributing what I can.

**Comment by js-ojus** [comment]
Resuming work on this project, based on feedback received.
